GET http://localhost:3000/movies

###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The shonen",
  "year": 2005,
  "director": "Jason Spilberg",
  "duration": 120,
  "poster": "https://ideogram.ai/assets/image/lossless/response/Ps-09as-TWW162yLyKBV4g",
  "genre": [ "Animation", "Fantasy" ]
}

###

GET http://localhost:3000/movies/2e6900e2-0b48-4fb6-ad48-09c7086e54fe

###

PATCH http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
  "year": 2000
}

###

DELETE http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

###
GET https://www.imdb.com/registration/is-user-recognized


###
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3